FORMAT: 1A

# DataStore

DataStore is a simple API allowing consumers to add generic items and look them up using queries.


## Items Collection [/items]

### List All Items [GET]

This generates a list of all available items

+ Response 200 (application/json)

        [
            {
                "key": "value"
            }
        ]

### Create a New Item [POST]

This allows creating a new item

+ Request (application/json)

        {
            "ley": "value"
        }

+ Response 201 (application/json)

    + Headers

            Location: /items/{item_id}

    + Body

            {
                "ley": "value"
            }


## Item [/items/{item_id}]

### Retrieve an Existing Item [GET]

This retrieves the specified item

+ Response 200 (application/json)

        [
            {
                "key": "value"
            }
        ]

### Update an Existing Item [PUT]

This allows updating an existing item

+ Request (application/json)

        {
            "key": "value"
        }

+ Response 201 (application/json)

    + Headers

            Location: /items/{item_id}

    + Body

            {
                "key": "value"
            }

### Delete an Exisiting Item [DELETE]

This allows removing an existing item

+ Response 204