FORMAT: 1A

# DataStore

DataStore is a simple API allowing consumers to add generic items and look them up using queries.


## Items Collection [/items]

### List All Items [GET]

This generates a list of all available items.

+ Request

    + Headers

            Range: items={lower_bound}:{upper_boud}

+ Response 200 (application/json)

        [
            {
                "id": 100,
                "key": "value"
            }
        ]

### Create a New Item [POST]

This allows creating a new item.

+ Request (application/json)

        {
            "key": "value"
        }

+ Response 201 (application/json)

    + Headers

            Location: /items/{item_id}

    + Body

            {
                "id": 100,
                "key": "value"
            }

## Items Metadata [/items/metadata]

### Read items metadata [GET]

This retrieves the metadata associated with the collection

+ Response 200 (application/json)

        {
            "tags" : [ "value" ]
        }

## Items Count [/items/count]

### Read items count [GET]

This retrieves the number of items in the collection

+ Response 200 (application/json)

        {
            "count": 10
        }

## Item Identifiers Collection [/items/identifiers]

### List All Items [GET]

This generates a list of identifiers for all available items.

+ Request

    + Headers

            Range: items={lower_bound}:{upper_boud}

+ Response 200 (application/json)

        [
            100
        ]

## Item [/items/{item_id}]

### Retrieve an Existing Item [GET]

This retrieves the specified item.

+ Response 200 (application/json)

    + Headers

            Last-Modified: {date}

    + Body

            {
                "id": 100,
                "key": "value"
            }

### Update an Existing Item [PUT]

This allows updating an existing item.

+ Request (application/json)

        {
            "id": 100,
            "key": "value"
        }

+ Response 200 (application/json)

        {
            "id": 100,
            "key": "value"
        }

### Delete an Exisiting Item [DELETE]

This allows removing an existing item.

+ Response 204